name: vuln
on:
  pull_request_target:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: './.github/workflows/reusable_workflow.yml'
